<a href="https://colab.research.google.com/github/mikodeperalta12/-Linear-Algebra_ChE_2nd-Sem-2021-2022/blob/main/Assignment4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Discussion

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

# Transposition

In [ ]:
A = np. array([
    [1, 2, 5],
    [5, -1, 0],
    [0, -3, 3]
])

In [ ]:
AT1 = np. transpose(A)
AT1

array([[ 1,  5,  0],
       [ 2, -1, -3],
       [ 5,  0,  3]])

In [ ]:
AT2 = A.T
AT2

array([[ 1,  5,  0],
       [ 2, -1, -3],
       [ 5,  0,  3]])

In [ ]:
np. array_equiv(AT1, AT2)

True

In [ ]:
B = np.array([
    [7, 3, 2, 1],
    [5, 6, 3, 1],
])
B. shape

(2, 4)

In [ ]:
np.transpose(B).shape

(4, 2)

In [ ]:
B. T. shape

(4, 2)

In [ ]:
M = np.array([
    [2, 4],
    [0, 8]
])
J = np.array([
    [-2, 0],
    [3, 6]
])

In [ ]:
np.array_equiv(M, J)

False

In [ ]:
np.dot(M, J)

array([[ 8, 24],
       [24, 48]])

In [ ]:
M.dot(J)

array([[ 8, 24],
       [24, 48]])

In [ ]:
M @ J

array([[ 8, 24],
       [24, 48]])

In [ ]:
M = np.array([
    [0, 7],
    [0, 5],
    [0, 1],
])
I = np.array([
    [0, 7],
    [2, 3],
    [1, 0]
])
K = np.array([
    [0, 1, 1],
    [1, 7, 7]
])

In [ ]:
M @ K

array([[ 7, 49, 49],
       [ 5, 35, 35],
       [ 1,  7,  7]])

In [ ]:
I @ K

array([[ 7, 49, 49],
       [ 3, 23, 23],
       [ 0,  1,  1]])

In [ ]:
M @I.T

array([[49, 21,  0],
       [35, 15,  0],
       [ 7,  3,  0]])