<a href="https://colab.research.google.com/github/mikodeperalta12/-Linear-Algebra_ChE_2nd-Sem-2021-2022/blob/main/Assignment_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Linear Algebra for ChE
##Assignment 3: Matrices



We'll try to look into further depth keeping in mind the basic understanding of Python.



###Objectives
At the end of this activity you will be able to:
1. Perform basic matrix computations. 
2. Understand matrices and how they relate to linear equations. 
3. Interpret and utilize matrix equations and operations.

# Discussion

In [8]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

$$
A = \left\{
    \begin{array}\
        x + y \\
        4x - 10y 
    \end{array}
    \right. \\
B = \left\{
    \begin{array}\
        x+y+z \\
        3x -2y -z \\
        -x + 4y +2z
    \end{array}
  \right. \\
C = \left\{
    \begin{array}\
        w-2x+3y-4z \\ 
        3w -x -2y + z \\
        2w- x +3y +2z \\
      \end{array}
\right. $$

         




:$$
A=\begin{bmatrix}\ 1 & 1 \\ 4 & {-10}\end{bmatrix} \\
B=\begin{bmatrix}\ 1 & 1 & 1 \\ 3 & -2 & -1 \\ -1 & 4 & 2\end
{bmatrix}\\
C=\begin{bmatrix}\ 1 & -2 & 3 & -4 \\ 3 & -1 & -2 & 1 \\ 2 & -1 & 3 & -2\end{bmatrix} 
$$




In [39]:
## Since we'll keep on describing matrices. Let's make a function.
def describe_mat(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [68]:
## Declaring a 4 x 5 matrix
L = np.array([[[[
    [96, 68, 33, 39, 51],
    [60, 19 ,30, 45, 86],
    [62, 57, 68, 93, 31],
    [57, 23, 19, 58, 23]
]]]])
describe_mat(L)

Matrix:
[[[[[96 68 33 39 51]
    [60 19 30 45 86]
    [62 57 68 93 31]
    [57 23 19 58 23]]]]]

Shape:	(1, 1, 1, 4, 5)
Rank:	5



In [69]:
N = np.array([[[
    [31, 32, 33, 34, 35],
    [41, 42, 53, 53, 13],
    [71, 24, 65, 73, 31],
    [31, 89, 13, 54, 14]
]]])
describe_mat(N)

Matrix:
[[[[31 32 33 34 35]
   [41 42 53 53 13]
   [71 24 65 73 31]
   [31 89 13 54 14]]]]

Shape:	(1, 1, 4, 5)
Rank:	4



In [70]:
E = np.array([[
    [81, 92, 73, 44, 35],
    [11, 22, 13, 63, 73],
    [71, 54, 45, 23, 41],
    [71, 89, 13, 84, 34]
]])
describe_mat(E)

Matrix:
[[[81 92 73 44 35]
  [11 22 13 63 73]
  [71 54 45 23 41]
  [71 89 13 84 34]]]

Shape:	(1, 4, 5)
Rank:	3



In [71]:
A = np.array([
    [32, 34, 37, 32, 36],
    [41, 42, 57, 52, 13],
    [71, 24, 65, 73, 31],
    [31, 89, 13, 54, 14]
])
describe_mat(A)

Matrix:
[[32 34 37 32 36]
 [41 42 57 52 13]
 [71 24 65 73 31]
 [31 89 13 54 14]]

Shape:	(4, 5)
Rank:	2



In [76]:
R = np.array([
    [31, 32, 33, 34, 35],
    [43, 42, 50, 57, 13],
    [72, 24, 65, 73, 39],
    [51, 89, 13, 74, 54]
  ]) 
describe_mat(R)


Matrix:
[[31 32 33 34 35]
 [43 42 50 57 13]
 [72 24 65 73 39]
 [51 89 13 74 54]]

Shape:	(4, 5)
Rank:	2

