<a href="https://colab.research.google.com/github/mikodeperalta12/-Linear-Algebra_ChE_2nd-Sem-2021-2022/blob/main/Assignment_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Linear Algebra for ChE
##Assignment 3: Matrices



We'll try to look into further depth keeping in mind the basic understanding of Python.



#Objectives
At the end of this activity you will be able to:
1. Perform basic matrix computations. 
2. Understand matrices and how they relate to linear equations. 
3. Interpret and utilize matrix equations and operations.

# Discussion

In [248]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

In [192]:
## Since we'll keep on describing matrices. Let's make a function.
def describe_mat(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [193]:
## Declaring a 4 x 5 matrix
L = np.array([[[[
    [96, 68, 33, 39, 51],
    [60, 19 ,30, 45, 86],
    [62, 57, 68, 93, 31],
    [57, 23, 19, 58, 23]
]]]])
describe_mat(L)

Matrix:
[[[[[96 68 33 39 51]
    [60 19 30 45 86]
    [62 57 68 93 31]
    [57 23 19 58 23]]]]]

Shape:	(1, 1, 1, 4, 5)
Rank:	5



In [194]:
N = np.array([[[
    [31, 32, 33, 34, 35],
    [41, 42, 53, 53, 13],
    [71, 24, 65, 73, 31],
    [31, 89, 13, 54, 14]
]]])
describe_mat(N)

Matrix:
[[[[31 32 33 34 35]
   [41 42 53 53 13]
   [71 24 65 73 31]
   [31 89 13 54 14]]]]

Shape:	(1, 1, 4, 5)
Rank:	4



In [195]:
E = np.array([[
    [81, 92, 73, 44, 35],
    [11, 22, 13, 63, 73],
    [71, 54, 45, 23, 41],
    [71, 89, 13, 84, 34]
]])
describe_mat(E)

Matrix:
[[[81 92 73 44 35]
  [11 22 13 63 73]
  [71 54 45 23 41]
  [71 89 13 84 34]]]

Shape:	(1, 4, 5)
Rank:	3



In [196]:
A = np.array([
    [32, 34, 37, 32, 36],
    [41, 42, 57, 52, 13],
    [71, 24, 65, 73, 31],
    [31, 89, 13, 54, 14]
])
describe_mat(A)

Matrix:
[[32 34 37 32 36]
 [41 42 57 52 13]
 [71 24 65 73 31]
 [31 89 13 54 14]]

Shape:	(4, 5)
Rank:	2



In [197]:
R = np.array([
    [31, 32, 33, 34, 35],
    [43, 42, 50, 57, 13],
    [72, 24, 65, 73, 39],
    [51, 89, 13, 74, 54]
  ]) 
describe_mat(R)


Matrix:
[[31 32 33 34 35]
 [43 42 50 57 13]
 [72 24 65 73 39]
 [51 89 13 74 54]]

Shape:	(4, 5)
Rank:	2



In [198]:
##  Decalaring a Row Matrix
row_mat_1D = np.array([
    [3, 2, 1, -5]
])  ## This is a 1-D matrix with a shape of (3,), which is not considered a row of matrix
row_mat_2D = np.array([
    [2, 4, 6, -1]
])   ## This is a 2-D matrix with a shape of (1,3)
describe_mat(row_mat_1D)
describe_mat(row_mat_2D)

Matrix:
[[ 3  2  1 -5]]

Shape:	(1, 4)
Rank:	2

Matrix:
[[ 2  4  6 -1]]

Shape:	(1, 4)
Rank:	2



In [199]:
## Declaring a column matrix

colmat = np.array([
    [3],
    [5],
    [7]
]) ## This is a 2-D Matrix with a shape of (3, 1)
describe_mat(colmat)

Matrix:
[[3]
 [5]
 [7]]

Shape:	(3, 1)
Rank:	2



###Categorizing Matrices
There are several ways of classifying matrices. Once could be according to their shape and another is according to their element values. We'll try to go through them.

#### Square Matrix
Square matrices are matrices that have the same row and column sizes. We could say a matrix is square if . We can tweak our matrix descriptor function to determine square matrices.

In [200]:
def describe_mat(matrix):
    is_square = True if matrix.shape[0] == matrix.shape[1] else False                                                     
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')

In [201]:
square_mat = np.array([
  [5, 3, 2, 1],
  [3, 2, 4, 9],
  [8, 4, 7, 5],
  [4, 8, 9, 1]
])
not_square_mat = np.array([
  [3, 4, 1, 4],
  [9, 6, 1, 3]
])
describe_mat (square_mat)
describe_mat (not_square_mat)

Matrix:
[[5 3 2 1]
 [3 2 4 9]
 [8 4 7 5]
 [4 8 9 1]]

Shape:	(4, 4)
Rank:	2
Is Square: True

Matrix:
[[3 4 1 4]
 [9 6 1 3]]

Shape:	(2, 4)
Rank:	2
Is Square: False



#### Null Matrix
A Null Matrix is a matrix that has no elements. It is always a subspace of any vector or matrix.

In [202]:
def describe_mat(matrix):
  if matrix.size > 0:
    is_square - True if matrix.shape[0] -- matrix.shape[1] else False
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
  else:
    print('Matrix is Null.')

In [203]:
null_mat = np.array([])
describe_mat(null_mat)

Matrix is Null.


#### Zero Matrix

In [204]:
zero_mat_row = np.zeros ((1,2))
zero_mat_sqr = np.zeros ((2,2))
zero_mat_rct = np.zeros ((3,2))

print(f'Zero Row Matrix: \n{zero_mat_row}')
print(f'Zero Square Matrix: \n{zero_mat_sqr}')
print(f'Zero Rectangular Matrix: \n{zero_mat_rct}')

Zero Row Matrix: 
[[0. 0.]]
Zero Square Matrix: 
[[0. 0.]
 [0. 0.]]
Zero Rectangular Matrix: 
[[0. 0.]
 [0. 0.]
 [0. 0.]]


####Ones Matrix


In [205]:
## Ones Matrix -  to get the identity

ones_mat_row = np.ones ((1,2))
ones_mat_sqr = np.ones ((2,2))
ones_mat_rct = np.ones ((3,2))

print(f'Ones Row Matrix: \n{ones_mat_row}')
print(f'Ones Square Matrix: \n{ones_mat_sqr}')
print(f'Ones Rectangular Matrix: \n{ones_mat_rct}')

Ones Row Matrix: 
[[1. 1.]]
Ones Square Matrix: 
[[1. 1.]
 [1. 1.]]
Ones Rectangular Matrix: 
[[1. 1.]
 [1. 1.]
 [1. 1.]]


#### Diagonal Matrix


In [206]:
## Diagonal Matrix
np.array([
   [2, 0, 0],
   [0, 2, 0],
   [0, 0, 2]
])
# a[1,1], a[2,2], a[3,3], ... a[n-1, n-1]

array([[2, 0, 0],
       [0, 2, 0],
       [0, 0, 2]])

In [207]:
#Other way to declare a diagonal matrix
d = np.diag([1, 9, 9, 7])
d

array([[1, 0, 0, 0],
       [0, 9, 0, 0],
       [0, 0, 9, 0],
       [0, 0, 0, 7]])

####Identity Matrix

In [208]:
#Identity Matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [209]:
#Other way to Declare an Identity Matrix
np.identity(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

####Upper Triangular Matrix

In [210]:
#Upper Triangular Matrix
np.array([
  [9, 0, 0, 0],
  [1, 3, 0, 0],
  [5, 3, 1, 0],
  [1, 3, 6, 8]
])

array([[9, 0, 0, 0],
       [1, 3, 0, 0],
       [5, 3, 1, 0],
       [1, 3, 6, 8]])

In [211]:
#Other Way to Declare Upper Triangular Matrix 
M = np.array([
    [32, -65, 15, -69, 20],
    [32, -65, 15, -69, 20],
    [32, -65, 15, -69, 20],
    [32, -65, 15, -69, 20],
    [32, -65, 15, -69, 20]
])
np. triu(E)


array([[[81, 92, 73, 44, 35],
        [ 0, 22, 13, 63, 73],
        [ 0,  0, 45, 23, 41],
        [ 0,  0,  0, 84, 34]]])

####Lower Triangular Matrix

In [212]:
#Lower Triangular Matrix 
np.array([
  [42, 0, 0, 0],
  [69, 42, 0, 0,],
  [69, 42, 42, 0],
  [69, 69, 69, 69]
])

array([[42,  0,  0,  0],
       [69, 42,  0,  0],
       [69, 42, 42,  0],
       [69, 69, 69, 69]])

In [213]:
#Other Way to Declare a Lower Triangular Matrix
np.tril (M)

array([[ 32,   0,   0,   0,   0],
       [ 32, -65,   0,   0,   0],
       [ 32, -65,  15,   0,   0],
       [ 32, -65,  15, -69,   0],
       [ 32, -65,  15, -69,  20]])

#Practice

Given the linear combination below, try to create a corresponding matrix representing it.

$$
\theta = 5x + 3y -z
$$

Given the system of linear combinations below, try to encode it as a matrix. Also describe the matrix.

$$
A = \left\{
    \begin{array}\
    x_1 + 2x_2 + x_3 \\
    4x_2 - x_3 \\
    10x_3
    \end{array}
\right. 
$$

In [ ]:
def describe_mat(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')
A = np.array ([
    [1, 2, 1],
    [-1, 4, 0],
    [10, 0 ,0]
])
A
describe_mat(A)

Given the matrix below, express it as a linear combination in a markdown.

G = np.array([ <br>
    [1,7,8], <br>
    [2,2,2], <br>
    [4,6,7] <br>
])

:$$
G=\begin{bmatrix} 1 & 7 & 8 \\ 2 & 2 & 2 \\ 4 & 6 &7\end{bmatrix} \\
$$


$$
G = \left\{
    \begin{array}\
    x_1 + 7x_2 + 8x_3\\
    2x_1 + 2x_2 + 2x_3 \\
    4x_1 + 6x_2 + 7x_3
    \end{array}
\right. 
$$

Given the matrix below, display the output as a LaTeX makdown also express it as a system of linear combinations. <br>
H = np.tril(G) <br>
H

array([[1, 0, 0], <br>
       [2, 2, 0], <br>
       [4, 6, 7]]) <br>

:$$
H=\begin{bmatrix} 1 & 0 & 0 \\ 2 & 2 & 0 \\ 4 & 6 &7\end{bmatrix} \\
$$

$$
H = \left\{
    \begin{array}\
    x_1  \\
    2x_1 - 2x_2 \\
    4x_1 + 6x_2 + 7x_3
    \end{array}
\right. 
$$

#### Matrix Algebra



#####Addition

In [214]:
#Declaring Matrix M and J and Addition of Matrices
M = np.array([
     [8, 24],
     [5, 0],
     [32, 10]
])
J = np.array([
     [12, 15],
     [0, 0],
     [23, 65]
])
M+J

array([[20, 39],
       [ 5,  0],
       [55, 75]])

In [215]:
3+M ####Broadcasting
#3*np.ones(J.shape)+M

array([[11, 27],
       [ 8,  3],
       [35, 13]])

In [216]:
#Other Way to Perform Addition of Matrices
np.add(M,J)

array([[20, 39],
       [ 5,  0],
       [55, 75]])

#####Subtraction

In [217]:
#Subtraction of Matrices
M-J

array([[ -4,   9],
       [  5,   0],
       [  9, -55]])

In [218]:
2-M
#2*np.ones(M.shape)-J

array([[ -6, -22],
       [ -3,   2],
       [-30,  -8]])

#####Element-wise Multiplication

In [219]:
#Element-wise Multiplication
M*J
#np.multiply(M,J)

array([[ 96, 360],
       [  0,   0],
       [736, 650]])

In [220]:
#Multiplication of a Constant and a Matrix
5*M

array([[ 40, 120],
       [ 25,   0],
       [160,  50]])

#####Element-wise Division

In [221]:
#Element-wise Division
M/J

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


array([[0.66666667, 1.6       ],
       [       inf,        nan],
       [1.39130435, 0.15384615]])

In [222]:
#Division Involving Matrices
omega=10**-2
M/(omega+J)

array([[6.66111574e-01, 1.59893404e+00],
       [5.00000000e+02, 0.00000000e+00],
       [1.39069970e+00, 1.53822489e-01]])

#Activity
This part is where we are given an output that involves our learnings about Matrices in Python

####Task 1
Create a function named mat_desc() that througouhly describes a matrix, it should:

Displays the shape, size, and rank of the matrix.<br>
Displays whether the matrix is square or non-square.<br>
Displays whether the matrix is an empty matrix.<br>
Displays if the matrix is an identity, ones, or zeros matrix

Use 5 sample matrices in which their shapes are not lower than (3,3) . In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [223]:
## Function Area 
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline
def describe_mat(matrix):
  if matrix.size > 0:
    if matrix.shape[0] == matrix.shape[1]:
      is_square = True
    else: 
      is_square = False
    if np.all(matrix == np.identity(matrix.shape[0])):
      sp = "Identity Matrix"
    elif np.all(matrix == np.zeros(matrix.shape)):
      sp = "Zero Matrix."
    elif np.all(matrix == np.ones(matrix.shape)):
      sp = "Ones Matrix."
    else:
      sp = "None."
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
  else:
    print('Matrix is Null.')
  
    

In [224]:
## Matrix Declarations
L = np.array([[[[
    [96, 68, 33, 39, 51],
    [60, 19 ,30, 45, 86],
    [62, 57, 68, 93, 31],
    [57, 23, 19, 58, 23]
]]]])

N = np.array([[[
    [31, 32, 33, 34, 35],
    [41, 42, 53, 53, 13],
    [71, 24, 65, 73, 31],
    [31, 89, 13, 54, 14]
]]])

E = np.array([[
    [81, 92, 73, 44, 35],
    [11, 22, 13, 63, 73],
    [71, 54, 45, 23, 41],
    [71, 89, 13, 84, 34]
]])

A = np.array([
    [32, 34, 37, 32, 36],
    [41, 42, 57, 52, 13],
    [71, 24, 65, 73, 31],
    [31, 89, 13, 54, 14]
])

R = np.array([
    [31, 32, 33, 34, 35],
    [43, 42, 50, 57, 13],
    [72, 24, 65, 73, 39],
    [51, 89, 13, 74, 54]
  ]) 

In [225]:
## Test Areas 

describe_mat(L)

describe_mat(N)

describe_mat(E)

describe_mat(A)

describe_mat(R)

Matrix:
[[[[[96 68 33 39 51]
    [60 19 30 45 86]
    [62 57 68 93 31]
    [57 23 19 58 23]]]]]

Shape:	(1, 1, 1, 4, 5)
Rank:	5
Is Square: True

Matrix:
[[[[31 32 33 34 35]
   [41 42 53 53 13]
   [71 24 65 73 31]
   [31 89 13 54 14]]]]

Shape:	(1, 1, 4, 5)
Rank:	4
Is Square: True

Matrix:
[[[81 92 73 44 35]
  [11 22 13 63 73]
  [71 54 45 23 41]
  [71 89 13 84 34]]]

Shape:	(1, 4, 5)
Rank:	3
Is Square: False

Matrix:
[[32 34 37 32 36]
 [41 42 57 52 13]
 [71 24 65 73 31]
 [31 89 13 54 14]]

Shape:	(4, 5)
Rank:	2
Is Square: False

Matrix:
[[31 32 33 34 35]
 [43 42 50 57 13]
 [72 24 65 73 39]
 [51 89 13 74 54]]

Shape:	(4, 5)
Rank:	2
Is Square: False



/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:12: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  if sys.path[0] == '':


###Task 2
Create a function named mat_operations() that takes in two matrices a input parameters it should:

Determines if the matrices are viable for operation and returns your own error message if they are not viable.<br>
Returns the sum of the matrices.<br>
Returns the differen of the matrices.<br>
Returns the element-wise multiplication of the matrices.<br>

Returns the element-wise division of the matrices.
Use 5 sample matrices in which their shapes are not lower than (3,3). In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [226]:
## Function Area
import numpy as np
def mat_operation(L, N):
  print(f'Matrix 1:\n {M} \n')
  print(f'Matrix 2:\n {J} \n')


  if(M.shape != J.shape):
    print('The shape of both matrices are not same. The system could not perform any operation.')
    return

  plus = M + J
  print(f'Sum of the chosen matrices:\n {plus} \n')

  minus = M - J
  print(f'Difference of the chosen matrices:\n {minus} \n')

  matpro = np.multiply(M, J)
  print(f'Element-wise multiplication of the chosen matrices:\n {matpro} \n')

  matdiv = np.divide(M, J)
  print(f'Element-wise division of the chosen matrices:\n {matdiv} \n')

In [227]:
## Matrix Declarations
M = np.array([
     [8, 24],
     [5, 0],
     [32, 10]
])
J = np.array([
     [12, 15],
     [0, 0],
     [23, 65]
])

In [228]:
## Test Areas
mat_operation(M, J)

Matrix 1:
 [[ 8 24]
 [ 5  0]
 [32 10]] 

Matrix 2:
 [[12 15]
 [ 0  0]
 [23 65]] 

Sum of the chosen matrices:
 [[20 39]
 [ 5  0]
 [55 75]] 

Difference of the chosen matrices:
 [[ -4   9]
 [  5   0]
 [  9 -55]] 

Element-wise multiplication of the chosen matrices:
 [[ 96 360]
 [  0   0]
 [736 650]] 

Element-wise division of the chosen matrices:
 [[0.66666667 1.6       ]
 [       inf        nan]
 [1.39130435 0.15384615]] 



/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: divide by zero encountered in true_divide
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in true_divide


#Conclusion